package com.example.demo;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int deleteByPrimaryKey(Integer cusNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    Customer selectByPrimaryKey(Integer cusNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_table
     *
     * @mbg.generated Fri Jul 03 11:09:12 JST 2020
     */
    int updateByPrimaryKey(Customer record);
}